//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynDataEntities.Entities
{
   using System;

   public partial class Order_Details_Extended
   {
      public int OrderID { get; set; }
      public int ProductID { get; set; }
      public string ProductName { get; set; }
      public decimal UnitPrice { get; set; }
      public short Quantity { get; set; }
      public float Discount { get; set; }
      public Nullable<decimal> ExtendedPrice { get; set; }
   }
}
