//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynDataEntities.Entities
{
   using System;

   public partial class Products_by_Category
   {
      public string CategoryName { get; set; }
      public string ProductName { get; set; }
      public string QuantityPerUnit { get; set; }
      public Nullable<short> UnitsInStock { get; set; }
      public bool Discontinued { get; set; }
   }
}
