//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynDataEntities.Entities
{
   using System.Collections.Generic;

   public partial class Shipper
   {
      public Shipper()
      {
         this.Orders = new HashSet<Order>();
      }

      public int ShipperID { get; set; }
      public string CompanyName { get; set; }
      public string Phone { get; set; }

      public virtual ICollection<Order> Orders { get; set; }
   }
}
