//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18449
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gallery.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить внешнюю учетную запись.
        /// </summary>
        public static string AddExternalAccount {
            get {
                return ResourceManager.GetString("AddExternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить изображение.
        /// </summary>
        public static string AddPictuteText {
            get {
                return ResourceManager.GetString("AddPictuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к профилю.
        /// </summary>
        public static string BackToProfileData {
            get {
                return ResourceManager.GetString("BackToProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма связывания.
        /// </summary>
        public static string BindingFormLegend {
            get {
                return ResourceManager.GetString("BindingFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свяжите свою учетную запись в.
        /// </summary>
        public static string BindYourAccountMessage {
            get {
                return ResourceManager.GetString("BindYourAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производитель.
        /// </summary>
        public static string CameraManufacturerString {
            get {
                return ResourceManager.GetString("CameraManufacturerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        public static string CameraModelString {
            get {
                return ResourceManager.GetString("CameraModelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить и вернуться к списку.
        /// </summary>
        public static string CancelAndBackToList {
            get {
                return ResourceManager.GetString("CancelAndBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма изменения пароля.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пароля.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение пароля.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание новой учетной записи.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий пароль.
        /// </summary>
        public static string CurrentPasswordMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string DateString {
            get {
                return ResourceManager.GetString("DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DeleteActionString {
            get {
                return ResourceManager.GetString("DeleteActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалите эти учетные данные {0} из своей учетной записи.
        /// </summary>
        public static string DeleteThisExternalAccounts {
            get {
                return ResourceManager.GetString("DeleteThisExternalAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя для данного адреса электронной почты уже существует. Введите другой адрес электронной почты..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string EditPicture {
            get {
                return ResourceManager.GetString("EditPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование картинки.
        /// </summary>
        public static string EditPictureTitle {
            get {
                return ResourceManager.GetString("EditPictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование профиля.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать профиль.
        /// </summary>
        public static string EditProfileData {
            get {
                return ResourceManager.GetString("EditProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при входе.
        /// </summary>
        public static string EnterError {
            get {
                return ResourceManager.GetString("EnterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось войти через службу.
        /// </summary>
        public static string EnterErrorMessage {
            get {
                return ResourceManager.GetString("EnterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить вход.
        /// </summary>
        public static string EnterYourself {
            get {
                return ResourceManager.GetString("EnterYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость выдержки.
        /// </summary>
        public static string ExposureTimeString {
            get {
                return ResourceManager.GetString("ExposureTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внешняя учетная запись удалена..
        /// </summary>
        public static string ExternalAccountHasDeleted {
            get {
                return ResourceManager.GetString("ExternalAccountHasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внешние службу проверки подлинности не настроены.
        /// </summary>
        public static string ExternalServicesStatus {
            get {
                return ResourceManager.GetString("ExternalServicesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось создать локальную учетную запись. Возможно, учетная запись &quot;{0}&quot; уже существует..
        /// </summary>
        public static string FailToCreateAccount {
            get {
                return ResourceManager.GetString("FailToCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл {0} сохранен.
        /// </summary>
        public static string FileHasSaved {
            get {
                return ResourceManager.GetString("FileHasSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} был удален.
        /// </summary>
        public static string FileWasDeleted {
            get {
                return ResourceManager.GetString("FileWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диафрагма: f/.
        /// </summary>
        public static string FNumberString {
            get {
                return ResourceManager.GetString("FNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фокус.
        /// </summary>
        public static string FocalString {
            get {
                return ResourceManager.GetString("FocalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галерея.
        /// </summary>
        public static string GalleryLinkText {
            get {
                return ResourceManager.GetString("GalleryLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на если у вас нет учетной записи.
        /// </summary>
        public static string IfYouDontHaveAccountMessage {
            get {
                return ResourceManager.GetString("IfYouDontHaveAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список изображений.
        /// </summary>
        public static string ImageList_Title {
            get {
                return ResourceManager.GetString("ImageList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО.
        /// </summary>
        public static string InitialsStrings {
            get {
                return ResourceManager.GetString("InitialsStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указан недопустимый ответ на вопрос для восстановления пароля. Проверьте значение и повторите попытку..
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указан недопустимый адрес электронной почты. Проверьте значение и повторите попытку..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указан недопустимый пароль. Введите допустимое значение пароля..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указан недопустимый вопрос для восстановления пароля. Проверьте значение и повторите попытку..
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указано недопустимое имя пользователя. Проверьте значение и повторите попытку..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить вход.
        /// </summary>
        public static string LoginActionText {
            get {
                return ResourceManager.GetString("LoginActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма входа.
        /// </summary>
        public static string LoginForm {
            get {
                return ResourceManager.GetString("LoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход через другую службу.
        /// </summary>
        public static string LoginOtherService {
            get {
                return ResourceManager.GetString("LoginOtherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войдите, используя свою учетную запись.
        /// </summary>
        public static string LoginUsingOwnAccount {
            get {
                return ResourceManager.GetString("LoginUsingOwnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галерея изображений.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление учетной записью.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальный размер изображения.
        /// </summary>
        public static string MaxPictureDim {
            get {
                return ResourceManager.GetString("MaxPictureDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальный размер изображения должен быть от 50 до 300 пискелей.
        /// </summary>
        public static string MaxPictureMeasurementError {
            get {
                return ResourceManager.GetString("MaxPictureMeasurementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мм..
        /// </summary>
        public static string MillimetersString {
            get {
                return ResourceManager.GetString("MillimetersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас нет локального пароля для этого сайта. Добавьте локальный пароль, чтобы входить без внешней учетной записи..
        /// </summary>
        public static string MissingLocalPassword {
            get {
                return ResourceManager.GetString("MissingLocalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно выбрать файл для загрузки.
        /// </summary>
        public static string NeedToSelectFileToUpload {
            get {
                return ResourceManager.GetString("NeedToSelectFileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет изображения.
        /// </summary>
        public static string NoPicture {
            get {
                return ResourceManager.GetString("NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указано.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество изображений на странице.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение должно быть в диапазоне от 5 до 50.
        /// </summary>
        public static string PageSizeMustBeIn {
            get {
                return ResourceManager.GetString("PageSizeMustBeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль и его подтверждение не совпадают..
        /// </summary>
        public static string PasswordAndHisConfirmedAreNotTheSame {
            get {
                return ResourceManager.GetString("PasswordAndHisConfirmedAreNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль изменен..
        /// </summary>
        public static string PasswordHasChanged {
            get {
                return ResourceManager.GetString("PasswordHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль задан..
        /// </summary>
        public static string PasswordIsSet {
            get {
                return ResourceManager.GetString("PasswordIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string PatronymicName {
            get {
                return ResourceManager.GetString("PatronymicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл {0} изменил описание.
        /// </summary>
        public static string PictureChangeDescription {
            get {
                return ResourceManager.GetString("PictureChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение.
        /// </summary>
        public static string PictureTitle {
            get {
                return ResourceManager.GetString("PictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string ProfileLinkText {
            get {
                return ResourceManager.GetString("ProfileLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставщик проверки подлинности вернул ошибку. Проверьте введенное значение и повторите попытку. Если проблему устранить не удастся, обратитесь к системному администратору..
        /// </summary>
        public static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрированные внешние учетные записи.
        /// </summary>
        public static string RegisteredExternalAccounts {
            get {
                return ResourceManager.GetString("RegisteredExternalAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма регистрации.
        /// </summary>
        public static string RegisterFormLegend {
            get {
                return ResourceManager.GetString("RegisterFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрируйтесь.
        /// </summary>
        public static string RegisterYourself {
            get {
                return ResourceManager.GetString("RegisterYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обработке запроса произошла ошибка.
        /// </summary>
        public static string RequestErrorMessage {
            get {
                return ResourceManager.GetString("RequestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сек.
        /// </summary>
        public static string SecondsString {
            get {
                return ResourceManager.GetString("SecondsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма задания пароля.
        /// </summary>
        public static string SetPasswordForm {
            get {
                return ResourceManager.GetString("SetPasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задать пароль.
        /// </summary>
        public static string SetPasswordSubmit {
            get {
                return ResourceManager.GetString("SetPasswordSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение выдержки.
        /// </summary>
        public static string ShutterSpeedValueString {
            get {
                return ResourceManager.GetString("ShutterSpeedValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла неизвестная ошибка. Проверьте введенное значение и повторите попытку. Если проблему устранить не удастся, обратитесь к системному администратору..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить новое изображение.
        /// </summary>
        public static string UploadNewPicture {
            get {
                return ResourceManager.GetString("UploadNewPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя уже существует. Введите другое имя пользователя..
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя для входа.
        /// </summary>
        public static string UserNameMessage {
            get {
                return ResourceManager.GetString("UserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя или пароль указаны неверно..
        /// </summary>
        public static string UserNameOrPasswordInvalid {
            get {
                return ResourceManager.GetString("UserNameOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос создания пользователя был отменен. Проверьте введенное значение и повторите попытку. Если проблему устранить не удастся, обратитесь к системному администратору..
        /// </summary>
        public static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение &quot;{0}&quot; должно содержать не менее {2} символов..
        /// </summary>
        public static string ValueMustGreaterOrEqualTwo {
            get {
                return ResourceManager.GetString("ValueMustGreaterOrEqualTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный текущий пароль или недопустимый новый пароль..
        /// </summary>
        public static string WrongCurrentOrNewPassword {
            get {
                return ResourceManager.GetString("WrongCurrentOrNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы прошли проверку через &lt;strong&gt;{0}&lt;/strong&gt;. Введите имя пользователя на этом сайте ниже и нажмите кнопку &quot;Подтвердить&quot;, чтобы завершить вход..
        /// </summary>
        public static string YouDoneCheckingFormatMessage {
            get {
                return ResourceManager.GetString("YouDoneCheckingFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы вошли как.
        /// </summary>
        public static string YouLoggedInAs {
            get {
                return ResourceManager.GetString("YouLoggedInAs", resourceCulture);
            }
        }
    }
}
