//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AXCarServer.rc
//
#define IDS_PROJNAME                    100
#define IDB_AXCAR                       101
#define IDR_AXCAR                       102
#define IDS_TITLEConfigureCar           103
#define IDS_HELPFILEConfigureCar        104
#define IDS_DOCSTRINGConfigureCar       105
#define IDR_CONFIGURECAR                106
#define IDD_CONFIGURECAR                107
#define IDB_LEMON1                      201
#define IDC_CHECKANIM                   201
#define IDB_LEMON2                      202
#define IDC_EDITNAME                    202
#define IDB_LEMON3                      203
#define IDC_EDITSPEED                   203
#define IDB_ALMOSTBLOWNUP               204
#define IDB_BLOWNUP                     205
#define IDD_ABOUTBOX                    206

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         203
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
