#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SatelliteMovingApp.Resource", IsApplication=true)]

namespace SatelliteMovingApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int FadeIn = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FadeInAfteDelay = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int GradualApproach = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int MenuItemGlow = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int MenuTitleColor = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int SettingsTitleColor = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int SplashTitleColor = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int VersionBackground = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int VersionColor = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070005
			public const int AboutTextPadding = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int AboutTextSize = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int MenuItemSize = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int MenuTitleSize = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int SettingsTitleSize = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int SplashTitleSize = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int VersionSize = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int VersionSpacing = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_satellite = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_satellite_alt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int divider = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int globe = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int half = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_search = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rect = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int satellite_first = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int satellite_fourth = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int satellite_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int satellite_second = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int satellite_third = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int textured = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090022
			public const int AboutMenuItemId = 2131296290;
			
			// aapt resource value: 0x7f090012
			public const int AddButtonId = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int DeleteButtonId = 2131296273;
			
			// aapt resource value: 0x7f090001
			public const int FirstHeaderImageViewId = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int FirstRelativeLayoutId = 2131296256;
			
			// aapt resource value: 0x7f09001e
			public const int GlobeImageViewId = 2131296286;
			
			// aapt resource value: 0x7f090004
			public const int HelpTextTextViewId = 2131296260;
			
			// aapt resource value: 0x7f090019
			public const int ImageViewBottomLeftId = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int ImageViewBottomRightId = 2131296282;
			
			// aapt resource value: 0x7f090016
			public const int ImageViewTopLeftId = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int ImageViewTopRightId = 2131296279;
			
			// aapt resource value: 0x7f090005
			public const int MainMenuTextView = 2131296261;
			
			// aapt resource value: 0x7f09000a
			public const int MenuBottomImageViewId = 2131296266;
			
			// aapt resource value: 0x7f090006
			public const int MenuHeaderImageViewFirstId = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int MenuHeaderImageViewSecondId = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int MenuListViewId = 2131296267;
			
			// aapt resource value: 0x7f090007
			public const int MenuTitleTextViewId = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int SatellitesInfoScrollViewId = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int SatellitesInfoTableLayoutId = 2131296272;
			
			// aapt resource value: 0x7f090013
			public const int SaveButtonId = 2131296275;
			
			// aapt resource value: 0x7f090003
			public const int SecondHeaderImageViewId = 2131296259;
			
			// aapt resource value: 0x7f090009
			public const int SecondRelativeLayoutId = 2131296265;
			
			// aapt resource value: 0x7f090021
			public const int SettingsMenuItemId = 2131296289;
			
			// aapt resource value: 0x7f09000e
			public const int SettingsTitleTextViewId = 2131296270;
			
			// aapt resource value: 0x7f09001b
			public const int SplashBottomTitleTextView = 2131296283;
			
			// aapt resource value: 0x7f09001d
			public const int SplashTopTitleTextView = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int SplashVersionTextView = 2131296284;
			
			// aapt resource value: 0x7f090020
			public const int StartMenuItemId = 2131296288;
			
			// aapt resource value: 0x7f090014
			public const int TableLayoutId = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int TableRow_1Id = 2131296277;
			
			// aapt resource value: 0x7f090018
			public const int TableRow_2Id = 2131296280;
			
			// aapt resource value: 0x7f090002
			public const int TextViewId = 2131296258;
			
			// aapt resource value: 0x7f09000d
			public const int TopLeftImageViewId = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int TopRightImageViewId = 2131296268;
			
			// aapt resource value: 0x7f09001f
			public const int action_search = 2131296287;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainMenuItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MenuScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SettingsScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SplashScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StartScreen = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int NavigateOptions = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000f
			public const int AboutTitle = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int AddBtnText = 2131034130;
			
			// aapt resource value: 0x7f050004
			public const int AppDesc = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int AppName = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int AppVersionInfo = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int DelBtnTxt = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int DemoString = 2131034123;
			
			// aapt resource value: 0x7f05001e
			public const int DistanceHelpText = 2131034142;
			
			// aapt resource value: 0x7f05001a
			public const int DistanceHint = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int DistanceTableHeader = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int EarthCollideError = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int EarthImageDesc = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int MainMenuTitle = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int MenuItemAbout = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int MenuItemSettings = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int MenuItemStart = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int NegativeDistanceError = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int NegativeTimeError = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int SatelliteCollideError = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int SatelliteImagesDesc = 2131034120;
			
			// aapt resource value: 0x7f05001f
			public const int SatellitesHaveNot = 2131034143;
			
			// aapt resource value: 0x7f050011
			public const int SaveBtnText = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int SettingsTopTitle = 2131034128;
			
			// aapt resource value: 0x7f05001d
			public const int SpeedHelpText = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int SpeedHint = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int SpeedTableHeader = 2131034139;
			
			// aapt resource value: 0x7f050006
			public const int SplashBottomTitle = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int SplashScreenActivityTitle = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int SplashTopTitle = 2131034117;
			
			// aapt resource value: 0x7f050018
			public const int TypeMismatchError = 2131034136;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
