#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SatelliteMovingApp.Resource", IsApplication=true)]

namespace SatelliteMovingApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_in_after_delay = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int gradual_approach = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int MenuItemGlow = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int MenuTitleColor = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int SettingsTitleColor = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int SplashTitleColor = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int VersionBackground = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int VersionColor = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060005
			public const int AboutTextPadding = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int AboutTextSize = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int MenuItemSize = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int MenuTitleSize = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int SettingsTitleSize = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int SplashTitleSize = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int VersionSize = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int VersionSpacing = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_satellite = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_satellite_alt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int divider = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int globe = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int half = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_search = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rect = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int satellite_first = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int satellite_fourth = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int satellite_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int satellite_second = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int satellite_third = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int textured = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090003
			public const int AboutMenuItemId = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int SettingsMenuItemId = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int StartMenuItemId = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int action_search = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SplashScreen = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int navigate_options = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07000d
			public const int AboutTitle = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int AddBtnText = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int AppDesc = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int AppName = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int AppVersionInfo = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int DelBtnTxt = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int DemoString = 2131165193;
			
			// aapt resource value: 0x7f07001c
			public const int DistanceHelpText = 2131165212;
			
			// aapt resource value: 0x7f070018
			public const int DistanceHint = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int DistanceTableHeader = 2131165210;
			
			// aapt resource value: 0x7f070012
			public const int EarthCollideError = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int EarthImageDesc = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int MainMenuTitle = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int MenuItemAbout = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int MenuItemSettings = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int MenuItemStart = 2131165194;
			
			// aapt resource value: 0x7f070015
			public const int NegativeDistanceError = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int NegativeTimeError = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int SatelliteCollideError = 2131165203;
			
			// aapt resource value: 0x7f070006
			public const int SatelliteImagesDesc = 2131165190;
			
			// aapt resource value: 0x7f07001d
			public const int SatellitesHaveNot = 2131165213;
			
			// aapt resource value: 0x7f07000f
			public const int SaveBtnText = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int SettingsTopTitle = 2131165198;
			
			// aapt resource value: 0x7f07001b
			public const int SpeedHelpText = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int SpeedHint = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int SpeedTableHeader = 2131165209;
			
			// aapt resource value: 0x7f070004
			public const int SplashBottomTitle = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int SplashScreenActivityTitle = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int SplashTopTitle = 2131165187;
			
			// aapt resource value: 0x7f070016
			public const int TypeMismatchError = 2131165206;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
