//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.DataLevel.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.PictureGalleries = new HashSet<PictureGallery>();
        }
    
        public int AccountId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<PictureGallery> PictureGalleries { get; set; }
    }
}
