//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

public static class Greater
{
public static Object Of(
	Object left, Object right)
{
	throw new ApplicationException("Type Object must implement one of the IComparable or IComparable<Object> interfaces");
}
public static Boolean Of(
	Boolean left, Boolean right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static Byte Of(
	Byte left, Byte right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static Char Of(
	Char left, Char right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static Decimal Of(
	Decimal left, Decimal right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static Double Of(
	Double left, Double right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static Single Of(
	Single left, Single right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static Int32 Of(
	Int32 left, Int32 right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static Int64 Of(
	Int64 left, Int64 right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static SByte Of(
	SByte left, SByte right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static Int16 Of(
	Int16 left, Int16 right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static String Of(
	String left, String right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static UInt32 Of(
	UInt32 left, UInt32 right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static UInt64 Of(
	UInt64 left, UInt64 right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
public static UInt16 Of(
	UInt16 left, UInt16 right)
{
	return left.CompareTo(right) < 0 ? right : left;
}
}