USE FreelanceIdentity
GO

IF EXISTS (
        SELECT * FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_NAME = 'UniqueEmail'
    )
    DROP TABLE UniqueEmail
    GO

CREATE TABLE UniqueEmail (
    EmailId INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Email VARCHAR(256) NOT NULL UNIQUE,
    AddDate DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_UniqueEmail_Users FOREIGN KEY (UserId) REFERENCES aspnet_Users (UserId)
        ON UPDATE CASCADE ON DELETE CASCADE
)
GO