//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AXShapesServer.rc
//
#define IDS_PROJNAME                    100
#define IDB_SHAPESCONTROL               101
#define IDR_SHAPESCONTROL               102
#define IDS_TITLECoCusomPage            103
#define IDS_HELPFILECoCusomPage         104
#define IDS_DOCSTRINGCoCusomPage        105
#define IDR_COCUSOMPAGE                 106
#define IDD_COCUSOMPAGE                 107
#define IDD_ABOUT                       201
#define IDC_EDITCAPTION                 201
#define IDC_RADIOCIRCLE                 202
#define IDC_RADIOSQUARE                 203
#define IDC_RADIORECT                   204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         205
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
