//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmsoHr.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsFeed
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public System.DateTime NewsDate { get; set; }
        public string RelatedLink { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    }
}
