//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmsoHr.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobVacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobVacancy()
        {
            this.JobVacancyMainResponsibilities = new HashSet<JobVacancyMainResponsibility>();
            this.JobVacancyMiscs = new HashSet<JobVacancyMisc>();
            this.JobVacancyRequirements = new HashSet<JobVacancyRequirement>();
            this.JobVacancyRestRequirements = new HashSet<JobVacancyRestRequirement>();
            this.JobVacancyWorkingConditions = new HashSet<JobVacancyWorkingCondition>();
        }
    
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public string LocationCity { get; set; }
        public decimal SalaryLevel { get; set; }
        public string WorkExperience { get; set; }
        public string EmploymentType { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobVacancyMainResponsibility> JobVacancyMainResponsibilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobVacancyMisc> JobVacancyMiscs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobVacancyRequirement> JobVacancyRequirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobVacancyRestRequirement> JobVacancyRestRequirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobVacancyWorkingCondition> JobVacancyWorkingConditions { get; set; }
    }
}
