//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaServiceSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racer
    {
        public Racer()
        {
            this.RaceResults = new HashSet<RaceResult>();
            this.YearResults = new HashSet<YearResult>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Starts { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
    
        public virtual ICollection<RaceResult> RaceResults { get; set; }
        public virtual ICollection<YearResult> YearResults { get; set; }
    }
}
