/*
    public override unsafe void ProcessUnsafe(int* pInt)
    {
        base.ProcessUnsafe(pInt);
    }

*/

MethodDeclaration(
    PredefinedType(
        Token(
            TriviaList(),
            SyntaxKind.VoidKeyword,
            TriviaList(
                Space
            )
        )
    ),
    Identifier("ProcessUnsafe")
)
.WithModifiers(
    TokenList(
        new []{
            Token(
                TriviaList(
                    Whitespace("    ")
                ),
                SyntaxKind.PublicKeyword,
                TriviaList(
                    Space
                )
            ),
            Token(
                TriviaList(),
                SyntaxKind.OverrideKeyword,
                TriviaList(
                    Space
                )
            ),
            Token(
                TriviaList(),
                SyntaxKind.UnsafeKeyword,
                TriviaList(
                    Space
                )
            )
        }
    )
)
.WithParameterList(
    ParameterList(
        SingletonSeparatedList<ParameterSyntax>(
            Parameter(
                Identifier("pInt")
            )
            .WithType(
                PointerType(
                    PredefinedType(
                        Token(SyntaxKind.IntKeyword)
                    )
                )
                .WithAsteriskToken(
                    Token(
                        TriviaList(),
                        SyntaxKind.AsteriskToken,
                        TriviaList(
                            Space
                        )
                    )
                )
            )
        )
    )
    .WithCloseParenToken(
        Token(
            TriviaList(),
            SyntaxKind.CloseParenToken,
            TriviaList(
                LineFeed
            )
        )
    )
)
.WithBody(
    Block(
        SingletonList<StatementSyntax>(
            ExpressionStatement(
                InvocationExpression(
                    MemberAccessExpression(
                        SyntaxKind.SimpleMemberAccessExpression,
                        BaseExpression()
                        .WithToken(
                            Token(
                                TriviaList(
                                    Whitespace("        ")
                                ),
                                SyntaxKind.BaseKeyword,
                                TriviaList()
                            )
                        ),
                        IdentifierName("ProcessUnsafe")
                    )
                )
                .WithArgumentList(
                    ArgumentList(
                        SingletonSeparatedList<ArgumentSyntax>(
                            Argument(
                                IdentifierName("pInt")
                            )
                        )
                    )
                )
            )
            .WithSemicolonToken(
                Token(
                    TriviaList(),
                    SyntaxKind.SemicolonToken,
                    TriviaList(
                        LineFeed
                    )
                )
            )
        )
    )
    .WithOpenBraceToken(
        Token(
            TriviaList(
                Whitespace("    ")
            ),
            SyntaxKind.OpenBraceToken,
            TriviaList(
                LineFeed
            )
        )
    )
    .WithCloseBraceToken(
        Token(
            TriviaList(
                Whitespace("    ")
            ),
            SyntaxKind.CloseBraceToken,
            TriviaList(
                LineFeed
            )
        )
    )
)