import "oaidl.idl";

// This is implemented by the coclass and called by
// the client.
//
[uuid(FA9D1723-6879-11d3-B929-0020781238D4), object]
interface ISomeInterface : IUnknown
{
	HRESULT TriggerEvent();
};

// This is implemented by the sink and called by the
// connectable coclass.
//
[uuid(FA9D1721-6879-11d3-B929-0020781238D4), object]
interface _IOutBound : IUnknown
{
	HRESULT Test();
};

[version(1.0), uuid(FA9D1720-6879-11d3-B929-0020781238D4)]
library RawConnServer
{
	importlib("stdole32.tlb");

	interface _IOutBound;
	
	[uuid(FA9D1722-6879-11d3-B929-0020781238D4)]
	coclass CoSomeObject
	{
		[default]interface ISomeInterface;
		[default, source] interface _IOutBound;
	};
};
