//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynDataEntities.Entities
{

   public partial class CategoryAudit
   {
      public int AuditID { get; set; }
      public int CategoryID { get; set; }
      public string OldName { get; set; }
      public string NEWNAME { get; set; }

      public virtual Category Category { get; set; }
   }
}
