//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLotEntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditRisk
    {
        public int CustId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
