#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QuizApp.Resource", IsApplication=true)]

namespace QuizApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int CustomAnim = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FadeIn = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int FadeIn2 = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int genders = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080007
			public const int error_color = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int logo_color = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int menu_color = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int menu_glow = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int title_color = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int title_glow = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int version_bkgrd = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int version_color = 2131230721;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090008
			public const int avatar_size = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int fav_place_textbox_size = 2131296265;
			
			// aapt resource value: 0x7f090005
			public const int game_question_size = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int help_text_padding = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int help_text_size = 2131296262;
			
			// aapt resource value: 0x7f090000
			public const int logo_size = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int menu_item_size = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int screen_title_size = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int version_size = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int version_spacing = 2131296258;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ActionSearch = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Avatar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bkgrnd = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Divider = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Half = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int LauncherWeb = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int NoQuestion = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int QuizIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Splash1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Splash2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Splash3 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Splash4 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Textured = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d002d
			public const int Button_DOB = 2131558445;
			
			// aapt resource value: 0x7f0d0003
			public const int Button_MapIt = 2131558403;
			
			// aapt resource value: 0x7f0d000d
			public const int Button_No = 2131558413;
			
			// aapt resource value: 0x7f0d0029
			public const int Button_Password = 2131558441;
			
			// aapt resource value: 0x7f0d000c
			public const int Button_Yes = 2131558412;
			
			// aapt resource value: 0x7f0d0026
			public const int EditText_Email = 2131558438;
			
			// aapt resource value: 0x7f0d0002
			public const int EditText_FavPlaceName = 2131558402;
			
			// aapt resource value: 0x7f0d0024
			public const int EditText_Nickname = 2131558436;
			
			// aapt resource value: 0x7f0d0018
			public const int EditText_Pwd1 = 2131558424;
			
			// aapt resource value: 0x7f0d001a
			public const int EditText_Pwd2 = 2131558426;
			
			// aapt resource value: 0x7f0d0022
			public const int ImageButton_Avatar = 2131558434;
			
			// aapt resource value: 0x7f0d000a
			public const int ImageSwitcher_QuestionImage = 2131558410;
			
			// aapt resource value: 0x7f0d0034
			public const int ImageView2_Left = 2131558452;
			
			// aapt resource value: 0x7f0d0035
			public const int ImageView2_Right = 2131558453;
			
			// aapt resource value: 0x7f0d0037
			public const int ImageView3_Left = 2131558455;
			
			// aapt resource value: 0x7f0d0038
			public const int ImageView3_Right = 2131558456;
			
			// aapt resource value: 0x7f0d0007
			public const int ImageView_Header = 2131558407;
			
			// aapt resource value: 0x7f0d0008
			public const int ImageView_Header2 = 2131558408;
			
			// aapt resource value: 0x7f0d000e
			public const int ImageView_Header3 = 2131558414;
			
			// aapt resource value: 0x7f0d000f
			public const int ImageView_Header4 = 2131558415;
			
			// aapt resource value: 0x7f0d0015
			public const int ImageView_MenuBottom = 2131558421;
			
			// aapt resource value: 0x7f0d0012
			public const int ImageView_MenuHeader = 2131558418;
			
			// aapt resource value: 0x7f0d0013
			public const int ImageView_MenuHeader2 = 2131558419;
			
			// aapt resource value: 0x7f0d002c
			public const int LinearLayout01 = 2131558444;
			
			// aapt resource value: 0x7f0d0028
			public const int LinearLayoutPassword = 2131558440;
			
			// aapt resource value: 0x7f0d0016
			public const int ListView_Menu = 2131558422;
			
			// aapt resource value: 0x7f0d0006
			public const int RelativeLayout01 = 2131558406;
			
			// aapt resource value: 0x7f0d0014
			public const int RelativeLayout02 = 2131558420;
			
			// aapt resource value: 0x7f0d0009
			public const int RelativeLayout_Content = 2131558409;
			
			// aapt resource value: 0x7f0d0021
			public const int ScrollView01 = 2131558433;
			
			// aapt resource value: 0x7f0d001d
			public const int ScrollViewAllScores = 2131558429;
			
			// aapt resource value: 0x7f0d001f
			public const int ScrollViewFriendScores = 2131558431;
			
			// aapt resource value: 0x7f0d0030
			public const int Spinner_Gender = 2131558448;
			
			// aapt resource value: 0x7f0d001c
			public const int TabHost1 = 2131558428;
			
			// aapt resource value: 0x7f0d0032
			public const int TableLayout01 = 2131558450;
			
			// aapt resource value: 0x7f0d001e
			public const int TableLayout_AllScores = 2131558430;
			
			// aapt resource value: 0x7f0d0020
			public const int TableLayout_FriendScores = 2131558432;
			
			// aapt resource value: 0x7f0d0033
			public const int TableRow01 = 2131558451;
			
			// aapt resource value: 0x7f0d0036
			public const int TableRow02 = 2131558454;
			
			// aapt resource value: 0x7f0d000b
			public const int TextSwitcher_QuestionText = 2131558411;
			
			// aapt resource value: 0x7f0d0010
			public const int TextView01 = 2131558416;
			
			// aapt resource value: 0x7f0d0039
			public const int TextViewBottomTitle = 2131558457;
			
			// aapt resource value: 0x7f0d003a
			public const int TextViewBottomVersion = 2131558458;
			
			// aapt resource value: 0x7f0d0031
			public const int TextViewTopTitle = 2131558449;
			
			// aapt resource value: 0x7f0d002b
			public const int TextView_DOB = 2131558443;
			
			// aapt resource value: 0x7f0d002e
			public const int TextView_DOB_Info = 2131558446;
			
			// aapt resource value: 0x7f0d0025
			public const int TextView_Email = 2131558437;
			
			// aapt resource value: 0x7f0d0001
			public const int TextView_FavPlace = 2131558401;
			
			// aapt resource value: 0x7f0d0004
			public const int TextView_FavPlaceCoords = 2131558404;
			
			// aapt resource value: 0x7f0d0005
			public const int TextView_FavPlaceCoords_Info = 2131558405;
			
			// aapt resource value: 0x7f0d002f
			public const int TextView_Gender = 2131558447;
			
			// aapt resource value: 0x7f0d0011
			public const int TextView_HelpText = 2131558417;
			
			// aapt resource value: 0x7f0d0023
			public const int TextView_Nickname = 2131558435;
			
			// aapt resource value: 0x7f0d0027
			public const int TextView_Password = 2131558439;
			
			// aapt resource value: 0x7f0d002a
			public const int TextView_Password_Info = 2131558442;
			
			// aapt resource value: 0x7f0d0017
			public const int TextView_Pwd1 = 2131558423;
			
			// aapt resource value: 0x7f0d0019
			public const int TextView_Pwd2 = 2131558425;
			
			// aapt resource value: 0x7f0d001b
			public const int TextView_PwdProblem = 2131558427;
			
			// aapt resource value: 0x7f0d003c
			public const int help_menu_item = 2131558460;
			
			// aapt resource value: 0x7f0d003d
			public const int results_menu_item = 2131558461;
			
			// aapt resource value: 0x7f0d0000
			public const int root = 2131558400;
			
			// aapt resource value: 0x7f0d003b
			public const int settings_menu_item = 2131558459;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FavPlaceDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Game = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Help = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MenuItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PasswordDialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Scores = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Splash = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int GameOptions = 2131492864;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int QuizHelp = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0002
			public const int Splash = 2131361794;
			
			// aapt resource value: 0x7f0a000d
			public const int all_scores = 2131361805;
			
			// aapt resource value: 0x7f0a0006
			public const int app_logo_bottom = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int app_logo_top = 2131361797;
			
			// aapt resource value: 0x7f0a0001
			public const int app_name = 2131361793;
			
			// aapt resource value: 0x7f0a0007
			public const int app_version_info = 2131361799;
			
			// aapt resource value: 0x7f0a002f
			public const int exit = 2131361839;
			
			// aapt resource value: 0x7f0a000e
			public const int friends_scores = 2131361806;
			
			// aapt resource value: 0x7f0a002a
			public const int gender_female = 2131361834;
			
			// aapt resource value: 0x7f0a0029
			public const int gender_male = 2131361833;
			
			// aapt resource value: 0x7f0a002b
			public const int gender_neutral = 2131361835;
			
			// aapt resource value: 0x7f0a0004
			public const int help = 2131361796;
			
			// aapt resource value: 0x7f0a0008
			public const int menu = 2131361800;
			
			// aapt resource value: 0x7f0a000c
			public const int menu_item_help = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int menu_item_play = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int menu_item_scores = 2131361803;
			
			// aapt resource value: 0x7f0a0009
			public const int menu_item_settings = 2131361801;
			
			// aapt resource value: 0x7f0a002d
			public const int no = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int no_questions = 2131361838;
			
			// aapt resource value: 0x7f0a000f
			public const int no_scores = 2131361807;
			
			// aapt resource value: 0x7f0a0000
			public const int quiz_game_title = 2131361792;
			
			// aapt resource value: 0x7f0a0011
			public const int rank = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int score = 2131361810;
			
			// aapt resource value: 0x7f0a0003
			public const int scores = 2131361795;
			
			// aapt resource value: 0x7f0a0015
			public const int settings = 2131361813;
			
			// aapt resource value: 0x7f0a001a
			public const int settings_button_dob = 2131361818;
			
			// aapt resource value: 0x7f0a0020
			public const int settings_button_favoriteplace = 2131361824;
			
			// aapt resource value: 0x7f0a0024
			public const int settings_button_favplace_map = 2131361828;
			
			// aapt resource value: 0x7f0a001b
			public const int settings_button_pwd = 2131361819;
			
			// aapt resource value: 0x7f0a0018
			public const int settings_dob = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int settings_dob_not_set = 2131361817;
			
			// aapt resource value: 0x7f0a0017
			public const int settings_email = 2131361815;
			
			// aapt resource value: 0x7f0a001f
			public const int settings_favoriteplace = 2131361823;
			
			// aapt resource value: 0x7f0a0021
			public const int settings_favoriteplace_not_set = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int settings_favplace_coords = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int settings_favplace_currentlocation = 2131361827;
			
			// aapt resource value: 0x7f0a001c
			public const int settings_gender = 2131361820;
			
			// aapt resource value: 0x7f0a0016
			public const int settings_nickname = 2131361814;
			
			// aapt resource value: 0x7f0a001d
			public const int settings_password = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int settings_password2 = 2131361822;
			
			// aapt resource value: 0x7f0a0028
			public const int settings_pwd_equal = 2131361832;
			
			// aapt resource value: 0x7f0a0027
			public const int settings_pwd_not_equal = 2131361831;
			
			// aapt resource value: 0x7f0a0026
			public const int settings_pwd_not_set = 2131361830;
			
			// aapt resource value: 0x7f0a0025
			public const int settings_pwd_set = 2131361829;
			
			// aapt resource value: 0x7f0a0010
			public const int username = 2131361808;
			
			// aapt resource value: 0x7f0a0013
			public const int wait_msg = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int wait_title = 2131361812;
			
			// aapt resource value: 0x7f0a002c
			public const int yes = 2131361836;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0000
			public const int AppTheme = 2131427328;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int AllScores = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int FriendScores = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SampleQuestions = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SampleQuestions2 = 2131034115;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
